### ISSUE TITLE
SSM agent now preinstalled in EKS AMI causes error with user data script

### ISSUE THREAD

**Issue by fitchtech** [aws-samples/logging-monitoring-apg-guide-examples#1]
https://github.com/aws-samples/logging-monitoring-apg-guide-examples/blob/7045b69c50dded1e18c523bbb27cbdf3bc6627e7/examples/eks/amazon_eks_managed_node_group_launch_config.yaml#L425

Now that the EKS optimized AMI has the SSM agent preinstalled this would throw an error. Cause bash set -ex is used the script exits on error before the bootstrap script runs. Therefore the nodes will not join the EKS cluster

**Comment by knizami** [comment]
Hello, thanks for presenting this issue.  In cases where the AMI ID provided already has SSM installed you can customize the launch template accordingly.  Instead of installing you may choose to update the SSM agent or to completely remove this part of the script.
